"""
One-step replacement for the three-stage mesh pipeline:

    (old)  niigz --[save_indexed_tif, 256-color split]--> separated .tif
           --[ImageJ 3D Viewer macro]--> separated .obj
           --[rename_objs + combine_objs]--> one named .obj

    (new)  niigz (+ name_dictionary.csv) --[skimage marching_cubes]--> one named, colored .obj/.mtl

Because the mesh is built per cell label directly in Python, none of the ImageJ
256-color machinery is needed: no intermediate tif, no map.txt / render_indexed.txt,
no rename/combine step. Each cell becomes one `g {name}_{label}` group with its own
material, all written into a single .obj + .mtl.

Colors reuse the same palette `P` as the old pipeline, indexed the same way ImageJ
saw the cell, so the per-cell colors match the previous output.
"""

import os
import glob

import numpy as np
import nibabel as nib
import pandas as pd
from scipy import ndimage
from skimage import measure
from skimage.transform import rescale

from utils.utils import P, check_folder


def _palette_rgb(label):
    """RGB (0-1) for a cell label, matching the color index the old tif pipeline used."""
    ci = (int(label) + 1) % 256
    if ci == 0:  # boundary case: the old `_000` group rendered these at middle_num
        ci = (int(label) + 1) // 256 + 1
    return P[3 * ci] / 255.0, P[3 * ci + 1] / 255.0, P[3 * ci + 2] / 255.0


def niigz_to_obj(niigz_path, obj_out_path, name_dictionary_path=None,
                 resize_scale=0.5, smooth_sigma=1.0, step_size=1, pad=2,
                 match_imagej=True):
    """Convert one segmented .nii.gz into a single named, colored .obj (+ .mtl).

    :param resize_scale: nearest-neighbor rescale of the label volume before meshing.
        0.5 matches the old `nifti2tiff_seperated` scale; use 1.0 for full resolution.
    :param smooth_sigma: gaussian smoothing of each cell's binary mask before marching
        cubes, replicating ImageJ "Show Color Surfaces ... radius=1". 0 disables it.
    :param step_size: marching_cubes step; >1 yields a coarser/lighter mesh.
    :param pad: voxels of padding around each cell's bounding box so the surface closes.
    :param match_imagej: emit vertices in the same coordinate frame as the old ImageJ
        pipeline. save_indexed_tif slices along axis2 and writes each page as
        Image.fromarray(data[...,z]), so the tif has rows=axis0, cols=axis1, slice=axis2;
        ImageJ then meshes with X=col=axis1, Y=row=axis0, Z=slice=axis2. Swapping
        axis0<->axis1 up front reproduces that exact vertex frame (verified against the
        original objs: centroid offset 0.1 vox, ~1 vox surface distance), keeping
        normals/winding self-consistent. Set False to keep raw niigz (axis0,axis1,axis2).
    """
    seg = np.rint(nib.load(niigz_path).get_fdata()).astype(np.int32)

    if match_imagej:
        seg = np.swapaxes(seg, 0, 1)

    if resize_scale != 1.0:
        # labels must never be blurred -> nearest neighbour (order=0)
        seg = rescale(seg, scale=resize_scale, order=0, preserve_range=True,
                      anti_aliasing=False).astype(np.int32)

    label_name = {}
    if name_dictionary_path and os.path.exists(name_dictionary_path):
        label_name = pd.read_csv(name_dictionary_path, index_col=0).to_dict()['0']

    labels = [lab for lab in np.unique(seg) if lab != 0]

    mtl_out_path = os.path.splitext(obj_out_path)[0] + '.mtl'
    check_folder(obj_out_path)

    # write to temp files first, rename only once both are complete; an interrupted
    # run then leaves only .tmp files, so a finished .obj is always whole (safe to skip).
    obj_tmp, mtl_tmp = obj_out_path + '.tmp', mtl_out_path + '.tmp'

    vertex_offset = 0
    n_cells = 0
    with open(obj_tmp, 'w') as fo, open(mtl_tmp, 'w') as fm:
        fo.write('# OBJ generated by niigz_to_obj.py\n')
        fo.write('mtllib {}\n'.format(os.path.basename(mtl_out_path)))
        fm.write('# MTL generated by niigz_to_obj.py\n\n')

        for lab in labels:
            # crop to the cell's bounding box (+pad) so marching cubes runs on a tiny
            # subvolume instead of the whole embryo -> orders of magnitude faster.
            coords = np.argwhere(seg == lab)
            lo = np.maximum(coords.min(0) - pad, 0)
            hi = np.minimum(coords.max(0) + pad + 1, seg.shape)
            sub = (seg[lo[0]:hi[0], lo[1]:hi[1], lo[2]:hi[2]] == lab).astype(np.float32)

            if smooth_sigma and smooth_sigma > 0:
                sub = ndimage.gaussian_filter(sub, sigma=smooth_sigma)

            try:
                verts, faces, normals, _ = measure.marching_cubes(
                    sub, level=0.5, step_size=step_size)
            except (ValueError, RuntimeError):
                continue  # cell too small to form a surface
            if len(verts) == 0:
                continue
            verts = verts + lo  # back into full-volume coordinates

            name = label_name.get(lab, 'NOTCELL')
            group = '{}_{}'.format(name, int(lab))
            r, g, b = _palette_rgb(lab)

            fo.write('g {}\n'.format(group))
            for v in verts:
                fo.write('v {:.4f} {:.4f} {:.4f}\n'.format(v[0], v[1], v[2]))
            for n in normals:
                fo.write('vn {:.4f} {:.4f} {:.4f}\n'.format(n[0], n[1], n[2]))
            fo.write('usemtl mat_{}\n'.format(group))
            for f in faces:
                a, bb, c = (int(f[0]) + 1 + vertex_offset,
                            int(f[1]) + 1 + vertex_offset,
                            int(f[2]) + 1 + vertex_offset)
                # vertices and normals are 1:1, so v-index == vn-index
                fo.write('f {a}//{a} {b}//{b} {c}//{c}\n'.format(a=a, b=bb, c=c))
            vertex_offset += len(verts)

            fm.write('newmtl mat_{}\n'.format(group))
            fm.write('Ka {:.4f} {:.4f} {:.4f}\n'.format(r, g, b))
            fm.write('Kd {:.4f} {:.4f} {:.4f}\n'.format(r, g, b))
            fm.write('Ks 0.0000 0.0000 0.0000\n')
            fm.write('d 1.0\n')
            fm.write('illum 1\n\n')
            n_cells += 1

    os.replace(obj_tmp, obj_out_path)  # atomic publish
    os.replace(mtl_tmp, mtl_out_path)

    print('  {} -> {} ({} cells, {} verts)'.format(
        os.path.basename(niigz_path), os.path.basename(obj_out_path), n_cells, vertex_offset))
    return obj_out_path, mtl_out_path


def batch_niigz_to_obj(embryo_names, root, target_root, name_dictionary_path,
                       seg_subfolder='SegCell', skip_existing=True, **kwargs):
    """Run niigz_to_obj over every {embryo}/{seg_subfolder}/*.nii.gz.

    :param skip_existing: when True, time points whose .obj already exists are skipped,
        so an interrupted batch can be resumed by simply re-running it.
    """
    for embryo_name in embryo_names:
        seg_root = os.path.join(root, embryo_name, seg_subfolder)
        niigz_paths = sorted(glob.glob(os.path.join(seg_root, '*.nii.gz')))
        print('{}: {} time points'.format(embryo_name, len(niigz_paths)))
        for niigz_path in niigz_paths:
            base = os.path.basename(niigz_path).split('.')[0]  # {embryo}_{tp}_segCell
            obj_out_path = os.path.join(target_root, embryo_name, base + '.obj')
            if skip_existing and os.path.exists(obj_out_path):
                print('  skip (exists): {}'.format(base + '.obj'))
                continue
            niigz_to_obj(niigz_path, obj_out_path, name_dictionary_path, **kwargs)


if __name__ == "__main__":
    # ---- single file ----
    niigz_to_obj(
        niigz_path=r'F:\My Drive\CMapSubmission\Dataset Access\Dataset C\WT_Sample4\SegCell\WT_Sample4_140_segCell.nii.gz',
        obj_out_path=r'C:\Users\User\Desktop\WT_Sample4_140_segCell.obj',
        name_dictionary_path=r'F:\My Drive\CMapSubmission\Dataset Access\Dataset C\name_dictionary.csv',
    )

    # ---- batch (replaces the whole 3-step pipeline) ----
    # skip_existing=True (default) makes this resumable: re-running skips finished .obj.
    # root = r'C:\Users\User\OneDrive - innocimda\CMapSubmission\Dataset Access\Dataset C'
    # batch_niigz_to_obj(
    #     embryo_names=['MT_lag-1_Sample1', 'MT_lag-1_Sample2', 'MT_pop-1_Sample1', 'MT_pop-1_Sample2'],
    #     root=root,
    #     target_root=r'C:\Users\User\OneDrive - innocimda\CMapSubmission\4 mutant output',
    #     name_dictionary_path=os.path.join(root, 'name_dictionary.csv'),
    #     seg_subfolder='SegCell',
    #     resize_scale=0.5,   # match old pipeline; set 1.0 for full resolution
    #     smooth_sigma=1.0,
    # )
